stages:
  - build
  - deploy

include:
  - project: chirpwireless/ci
    file: general.yaml
  - project: chirpwireless/ci
    file: build-image.yaml
  - project: chirpwireless/ci
    file: helm.yaml
  - project: chirpwireless/ci
    file: deploy-gke-staging.yaml

variables:
  IMAGE_NAME: registry.gitlab.com/chirpwireless/docs
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  HELM_CHART_PATH: ./charts/docs
  HELM_RELEASE_NAME: docs

build:
  extends: 
    - .default
    - .build-image
  when: manual
  stage: build

deploy:staging:
  stage: deploy
  environment:
    name: staging
  variables:
    NAMESPACE: staging
    url: https://docs.staging.chirpwireless.io
    VALUES_FILE: ./charts/values/staging.yaml
  extends:
    - .deploy-gke-staging
  needs:
    - build


deploy:prod:
  stage: deploy
  environment:
    name: prod
    url: https://docs.prod.internal.chirpwireless.io
  variables:
    EKS_CLUSTER_NAME: prod
    NAMESPACE: docs
    VALUES_FILE: ./charts/values/prod.yaml
  extends:
    - .default
    - .helm-deploy
  needs:
    - build
