stages:
  - build
  - deploy

include:
  - project: chirpwireless/ci
    file: general.yaml
  - project: chirpwireless/ci
    file: build-image.yaml
  - project: chirpwireless/ci
    file: helm.yaml


variables:
  IMAGE_NAME: registry.gitlab.com/chirpwireless/docs
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  HELM_CHART_PATH: ./charts/docs
  HELM_RELEASE_NAME: docs

build-crypto:
  extends: 
    - .default
    - .build-image
  when: manual
  stage: build
  variables:
    IMAGE_TAG: crypto-$CI_COMMIT_SHORT_SHA

build-iot:
  extends: 
    - .default
    - .build-image
  when: manual
  before_script:
    - if [ -z "${IMAGE_NAME}" ]; then echo "Missing required variable \$IMAGE_NAME" && exit 1; fi;
    - python3 /autoversion.py
    - source .env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - cp Dockerfile-iot Dockerfile
  stage: build
  variables:
    IMAGE_TAG: iot_$CI_COMMIT_SHORT_SHA



deploy-crypto:staging:
  stage: deploy
  environment:
    name: staging
    url: http://docs.internal.chirpwireless.io
  variables:
    EKS_CLUSTER_NAME: staging
    NAMESPACE: staging
    VALUES_FILE: ./charts/values/crypto-wiki/staging.yaml
    HELM_RELEASE_NAME: docs-crypto
    VERSION: crypto-$CI_COMMIT_SHORT_SHA
  extends:
    - .default
    - .helm-deploy
  needs:
    - build-crypto

deploy-iot:staging:
  stage: deploy
  environment:
    name: staging
    url: http://docs-iot.internal.chirpwireless.io
  variables:
    EKS_CLUSTER_NAME: staging
    NAMESPACE: staging
    VALUES_FILE: ./charts/values/iot-wiki/staging.yaml
    HELM_RELEASE_NAME: docs-iot
    VERSION: iot-$CI_COMMIT_SHORT_SHA
  extends:
    - .default
    - .helm-deploy
  needs:
    - build-iot

##deploy:prod:
#  stage: deploy
#  environment:
#    name: prod
#    url: https://docs.prod.internal.chirpwireless.io
#  variables:
#    EKS_CLUSTER_NAME: prod
#    NAMESPACE: docs
#    VALUES_FILE: ./charts/values/prod.yaml
#  extends:
#    - .default
#    - .helm-deploy
#  needs:
#    - build
